apiVersion: apps/v1
kind: Deployment
metadata:
  name: threetier-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app : backend
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend
    spec:
      containers:
        - image: sumanttate/3tierapp-backend:latest
          name: backend
          ports:
            - containerPort: 3500
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-svc:27017/todo?directConnection=true
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
            

