apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: sumanttate/3tierapp-frontend:latest
          ports:
            - containerPort: 3000
          env: 
             - name: REACT_APP_BACKEND_URL
               value: "http://backend.amanpathakdevops.study/api/tasks"

